[package]
name = "pvb"
version = "0.1.0"
edition = "2018"

[dependencies]
serde_json = "1.0"
clap = "3.0"
regex = "1.5.4"
git2 = "0.18.2"
serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
rusty-hook = "^0.11.2"
